module.exports.folderFlow = {
  current_backup: "previous_backup_one",
  previous_backup_one: "previous_backup_two",
  previous_backup_two: "previous_backup_three",
  previous_backup_three: "previous_backup_four",
  previous_backup_four: "previous_backup_five",
  previous_backup_five: "previous_backup_six",
  previous_backup_six: "previous_backup_seven",
  previous_backup_seven: "previous_backup_eight",
  previous_backup_eight: "previous_backup_four",
  previous_backup_eight: "previous_backup_nine",
  previous_backup_nine: "previous_backup_ten",
  previous_backup_ten: "previous_backup_eleven",
  previous_backup_eleven: "previous_backup_twelve",
  previous_backup_twelve: "previous_backup_thirteen",
  previous_backup_thirteen: "previous_backup_fourteen",
  previous_backup_fourteen: "previous_backup_fifteen",
  previous_backup_fifteen: "previous_backup_sixteen",
  previous_backup_sixteen: "previous_backup_seventeen",
  previous_backup_seventeen: "previous_backup_eighteen",
  previous_backup_eighteen: "previous_backup_nineteen",
  previous_backup_nineteen: "previous_backup_twenty",
  previous_backup_twenty: "previous_backup_twentyone",
  previous_backup_twentyone: "previous_backup_twentytwo",
  previous_backup_twentytwo: "previous_backup_twentythree",
};
